Perceptron on training data

Student Study Hours-0(Fail)|1(Pass)

In [1]:
import numpy as np

In [2]:
X=np.array([1,2,3,4]) #study hours
y=np.array([0,0,1,1]) #fail(0),pass(1)
X,y

(array([1, 2, 3, 4]), array([0, 0, 1, 1]))

In [3]:
w=0.0
b=0.0
learning_rate=1
epochs=5

print("Initial Weight:",w)
print("Initial Bias:",b)


Initial Weight: 0.0
Initial Bias: 0.0


Define Activation Function(Step Function)

In [4]:
def step_function(z):
    return 1 if z>=0 else 0


Training Loop

In [5]:
for epoch in range(epochs):
    print(f"\nEpoch {epoch+1}")
    for i in range(len(X)):
        #1. Compute Weighted sum
        z=w*X[i]+b
        #2. Apply Activation function
        y_pred=step_function(z)
        #3. Compute Error
        error=y[i]-y_pred
        #4.Updated Weight
        w=w + learning_rate*error*X[i]
        #5. Update Bias
        b=b + learning_rate*error
        print(f"Input:{X[i]}, Predicted:{y_pred}, Actual: {y[i]},w:{w},b:{b}")
    


Epoch 1
Input:1, Predicted:1, Actual: 0,w:-1.0,b:-1.0
Input:2, Predicted:0, Actual: 0,w:-1.0,b:-1.0
Input:3, Predicted:0, Actual: 1,w:2.0,b:0.0
Input:4, Predicted:1, Actual: 1,w:2.0,b:0.0

Epoch 2
Input:1, Predicted:1, Actual: 0,w:1.0,b:-1.0
Input:2, Predicted:1, Actual: 0,w:-1.0,b:-2.0
Input:3, Predicted:0, Actual: 1,w:2.0,b:-1.0
Input:4, Predicted:1, Actual: 1,w:2.0,b:-1.0

Epoch 3
Input:1, Predicted:1, Actual: 0,w:1.0,b:-2.0
Input:2, Predicted:1, Actual: 0,w:-1.0,b:-3.0
Input:3, Predicted:0, Actual: 1,w:2.0,b:-2.0
Input:4, Predicted:1, Actual: 1,w:2.0,b:-2.0

Epoch 4
Input:1, Predicted:1, Actual: 0,w:1.0,b:-3.0
Input:2, Predicted:0, Actual: 0,w:1.0,b:-3.0
Input:3, Predicted:1, Actual: 1,w:1.0,b:-3.0
Input:4, Predicted:1, Actual: 1,w:1.0,b:-3.0

Epoch 5
Input:1, Predicted:0, Actual: 0,w:1.0,b:-3.0
Input:2, Predicted:0, Actual: 0,w:1.0,b:-3.0
Input:3, Predicted:1, Actual: 1,w:1.0,b:-3.0
Input:4, Predicted:1, Actual: 1,w:1.0,b:-3.0


In [6]:
print("Final Weight:",w)
print("Final Bias:",b)

Final Weight: 1.0
Final Bias: -3.0


Testing the Model

In [7]:
for i in range(len(X)):
    z=np.dot(w,X[i])+b
    prediction=step_function(z)
    print("Input",X[i],"Prediction:",prediction)

Input 1 Prediction: 0
Input 2 Prediction: 0
Input 3 Prediction: 1
Input 4 Prediction: 1


Perceptron OR gate

In [8]:
X=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y=np.array([0,1,1,1])
X,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 1]))

In [9]:
w=np.zeros(2)
b=0
learning_rate=0.1
epochs=10
print("Initial Weights:",w)
print("Initial Bias:",b)

Initial Weights: [0. 0.]
Initial Bias: 0


In [10]:
def step_function(z):
    return 1 if z>=0 else 1

In [11]:
print("\n Testing OR Gate")
for epoch in range(epochs):
    print(f"\Epoch {epoch+1}")
    for i in range(len(X)):
        #1
        z=np.dot(w,X[i])+b
        #2.
        y_pred=step_function(z)
        #3.
        error=y[i]-y_pred
        #4.
        w+=learning_rate*error*X[i]
        #5.
        b+=learning_rate*error
        print(f"Input:{X[i]},Predited:{y_pred}, Actual:{y[i]},w:{w},b:{b}")


 Testing OR Gate
\Epoch 1
Input:[0 0],Predited:1, Actual:0,w:[0. 0.],b:-0.1
Input:[0 1],Predited:1, Actual:1,w:[0. 0.],b:-0.1
Input:[1 0],Predited:1, Actual:1,w:[0. 0.],b:-0.1
Input:[1 1],Predited:1, Actual:1,w:[0. 0.],b:-0.1
\Epoch 2
Input:[0 0],Predited:1, Actual:0,w:[0. 0.],b:-0.2
Input:[0 1],Predited:1, Actual:1,w:[0. 0.],b:-0.2
Input:[1 0],Predited:1, Actual:1,w:[0. 0.],b:-0.2
Input:[1 1],Predited:1, Actual:1,w:[0. 0.],b:-0.2
\Epoch 3
Input:[0 0],Predited:1, Actual:0,w:[0. 0.],b:-0.30000000000000004
Input:[0 1],Predited:1, Actual:1,w:[0. 0.],b:-0.30000000000000004
Input:[1 0],Predited:1, Actual:1,w:[0. 0.],b:-0.30000000000000004
Input:[1 1],Predited:1, Actual:1,w:[0. 0.],b:-0.30000000000000004
\Epoch 4
Input:[0 0],Predited:1, Actual:0,w:[0. 0.],b:-0.4
Input:[0 1],Predited:1, Actual:1,w:[0. 0.],b:-0.4
Input:[1 0],Predited:1, Actual:1,w:[0. 0.],b:-0.4
Input:[1 1],Predited:1, Actual:1,w:[0. 0.],b:-0.4
\Epoch 5
Input:[0 0],Predited:1, Actual:0,w:[0. 0.],b:-0.5
Input:[0 1],Predited:1,

<>:3: SyntaxWarning: invalid escape sequence '\E'
<>:3: SyntaxWarning: invalid escape sequence '\E'
C:\Users\lekha\AppData\Local\Temp\ipykernel_11848\3785571371.py:3: SyntaxWarning: invalid escape sequence '\E'
  print(f"\Epoch {epoch+1}")


In [12]:
print("Final Weights:",w)
print("Final Bias:",b)

Final Weights: [0. 0.]
Final Bias: -0.9999999999999999


In [13]:
print("\n Testing OR Gate")
for i in range(len(X)):
    z=np.dot(w,X[i])+b
    prediction=step_function(z)
    print("Input",X[i],"Prediction:",prediction)


 Testing OR Gate
Input [0 0] Prediction: 1
Input [0 1] Prediction: 1
Input [1 0] Prediction: 1
Input [1 1] Prediction: 1
